name: PR Checklist Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read
  contents: read

jobs:
  checklist-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR task list completed
        uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: ${{ secrets.TOKEN }}
