name: Deploy Auto Environment

on:
  push:
    branches:
      - develop
      - staging
      - product
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: write
      id-token: write

    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      ENV: ${{ vars.ENV }}
      KEY: ${{ vars.KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Show current environment info
        run: |
          echo "Deploying branch: ${{ github.ref_name }}"
          echo "Using GitHub Environment: ${{ github.ref_name == 'develop' && 'dev' || 'staging' || 'prod' }}"
          echo "GCP_PROJECT_ID = $GCP_PROJECT_ID"

      - name: Show 2
        run: |
          echo "Show env"
          echo "$ENV" | tee .env
          cat .env
      - name: show secrets
        run: |
          echo "Secret: $KEY"

      - name: Generate beautiful IMAGE_TAG
        id: tag
        run: |
          # Lấy 7 ký tự đầu của commit SHA
          COMMIT=$(git rev-parse --short=7 HEAD)
          
          # Tạo định dạng thời gian: HH.MM.DDMMYY
          TIME=$(date +"%H.%M.%d%m%y")
          
          # Gán tag cuối cùng
          IMAGE_TAG="${COMMIT}-${TIME}"
          
          # In ra để debug
          echo "Commit SHA : $COMMIT"
          echo "Time       : $TIME"
          echo "IMAGE_TAG  : $IMAGE_TAG"
          
          # Đưa ra output để các step sau dùng: ${{ steps.tag.outputs.IMAGE_TAG }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Output
        run: |
          echo "Đã đẩy image với tag: ${{ steps.tag.outputs.IMAGE_TAG }}"
